# Generated by Django 4.1 on 2022-11-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_slider_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('fblink', models.CharField(max_length=255)),
                ('instalink', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/team/%Y/%M/%d/')),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
