# Generated by Django 4.1 on 2022-11-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='media/team/%Y/%m/%d/'),
        ),
    ]
