# Generated by Django 4.1 on 2022-11-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_alter_team_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ytlink',
            field=models.CharField(default='ytlink', max_length=255),
            preserve_default=False,
        ),
    ]
