# Generated by Django 4.1 on 2022-11-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_alter_contact_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
