# Generated by Django 4.1 on 2022-11-20 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_alter_youtuber_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('comedy', 'comedy'), ('gaming', 'gaming'), ('code', 'code'), ('bikes', 'bikes'), ('cooking', 'cooking'), ('sport', 'sport')], default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='camera',
            field=models.CharField(choices=[('nikon', 'nikon'), ('fuji', 'fuji'), ('canon', 'canon'), ('panasonic', 'panasonic')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 20, 11, 32, 28, 277488)),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], max_length=255),
        ),
    ]
