# Generated by Django 4.1 on 2022-11-20 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0004_alter_youtuber_created_on_alter_youtuber_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 20, 12, 56, 27, 84228)),
        ),
    ]
